//! bat syntax highlighter theme generator.
//!
//! Produces `bat/garden.tmTheme` — a TextMate theme in XML plist format
//! that bat uses for syntax highlighting. After placing the file, run
//! `bat cache --build` to register it.
//!
//! # Color mapping (global settings)
//!
//! | tmTheme key     | Palette role  | Rationale               |
//! |-----------------|--------------|-------------------------|
//! | `background`    | `base`       | Editor background       |
//! | `foreground`    | `text-2`     | Default body text       |
//! | `caret`         | `text-1`     | Cursor color            |
//! | `selection`     | `base-hl`    | Selection highlight     |
//! | `lineHighlight` | `base-raised`| Current line highlight  |
//!
//! # Scope rules
//!
//! | Scope                        | Color    | Style     |
//! |------------------------------|----------|-----------|
//! | `comment`                    | `text-4` | italic    |
//! | `string`                     | `ok`     |           |
//! | `constant`                   | `accent` |           |
//! | `keyword`, `storage`         | `text-3` |           |
//! | `entity.name.function`       | `text-1` |           |
//! | `variable`                   | `text-1` |           |
//! | `entity.name.type`, `support.type` | `text-2` | bold |
//! | `entity.name.tag`            | `text-3` |           |
//! | `entity.other.attribute-name`| `accent` |           |
//! | `punctuation`                | `text-3` |           |
//! | `markup.heading`             | `text-1` | bold      |
//! | `markup.underline.link`      | `accent` | underline |
//! | `invalid`                    | `urgent` |           |
//! | `entity.name.section`        | `text-1` | bold      |
//! | `meta.preprocessor`          | `accent` |           |

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// bat theme generator.
pub struct Bat;

impl ThemeGenerator for Bat {
    fn name(&self) -> &str {
        "bat"
    }

    fn relative_path(&self) -> &str {
        "bat/garden.tmTheme"
    }

    fn generate(&self, palette: &Palette) -> String {
        let c = |role: ColorRole| palette.color(role).unwrap().as_str();

        let base = c(ColorRole::Base);
        let base_raised = c(ColorRole::BaseRaised);
        let base_hl = c(ColorRole::BaseHl);
        let text1 = c(ColorRole::Text1);
        let text2 = c(ColorRole::Text2);
        let text3 = c(ColorRole::Text3);
        let text4 = c(ColorRole::Text4);
        let accent = c(ColorRole::Accent);
        let urgent = c(ColorRole::Urgent);
        let ok = c(ColorRole::Ok);

        format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Garden theme — {name} {icon} -->
<!-- Generated by garden-themes. Do not edit by hand. -->
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Garden — {name}</string>
	<key>settings</key>
	<array>
		<dict>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>{base}</string>
				<key>foreground</key>
				<string>{text2}</string>
				<key>caret</key>
				<string>{text1}</string>
				<key>selection</key>
				<string>{base_hl}</string>
				<key>lineHighlight</key>
				<string>{base_raised}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Comment</string>
			<key>scope</key>
			<string>comment</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{text4}</string>
				<key>fontStyle</key>
				<string>italic</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>String</string>
			<key>scope</key>
			<string>string</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{ok}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Constant</string>
			<key>scope</key>
			<string>constant</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{accent}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Keyword</string>
			<key>scope</key>
			<string>keyword</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{text3}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Storage</string>
			<key>scope</key>
			<string>storage</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{text3}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Function</string>
			<key>scope</key>
			<string>entity.name.function</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{text1}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Variable</string>
			<key>scope</key>
			<string>variable</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{text1}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Type</string>
			<key>scope</key>
			<string>entity.name.type, support.type</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{text2}</string>
				<key>fontStyle</key>
				<string>bold</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Tag</string>
			<key>scope</key>
			<string>entity.name.tag</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{text3}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Attribute</string>
			<key>scope</key>
			<string>entity.other.attribute-name</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{accent}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Punctuation</string>
			<key>scope</key>
			<string>punctuation</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{text3}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Heading</string>
			<key>scope</key>
			<string>markup.heading, entity.name.section</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{text1}</string>
				<key>fontStyle</key>
				<string>bold</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Link</string>
			<key>scope</key>
			<string>markup.underline.link</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{accent}</string>
				<key>fontStyle</key>
				<string>underline</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Invalid</string>
			<key>scope</key>
			<string>invalid</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{urgent}</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Preprocessor</string>
			<key>scope</key>
			<string>meta.preprocessor</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>{accent}</string>
			</dict>
		</dict>
	</array>
</dict>
</plist>
"#,
            name = palette.name,
            icon = palette.icon,
        )
    }
}
