//! btop system monitor theme generator.
//!
//! Produces `btop/garden.theme` — a btop theme file using the
//! `theme[key]="value"` format.
//!
//! # Color mapping
//!
//! | btop key              | Palette role  | Rationale                |
//! |-----------------------|--------------|--------------------------|
//! | `main_bg`             | `base`       | Main background          |
//! | `main_fg`             | `text-2`     | Main foreground          |
//! | `title`               | `text-1`     | Box titles               |
//! | `hi_fg`               | `accent`     | Highlighted text         |
//! | `selected_bg`         | `base-hl`    | Selected item background |
//! | `selected_fg`         | `text-1`     | Selected item foreground |
//! | `inactive_fg`         | `text-4`     | Inactive/dim text        |
//! | `proc_misc`           | `text-3`     | Misc process info        |
//! | `cpu_box`, `mem_box`, etc. | `border` | Box border colors       |
//! | `div_line`            | `border-sub` | Divider lines            |
//! | `temp_start`          | `accent`     | Temp gradient start      |
//! | `temp_mid`            | `urgent`     | Temp gradient mid        |
//! | `temp_end`            | `urgent`     | Temp gradient end        |
//! | `cpu_start`           | `accent`     | CPU gradient start       |
//! | `cpu_mid`             | `ok`         | CPU gradient mid         |
//! | `cpu_end`             | `urgent`     | CPU gradient end         |
//! | `free_start`          | `ok`         | Free memory start        |
//! | `free_mid`            | `accent`     | Free memory mid          |
//! | `free_end`            | `text-3`     | Free memory end          |
//! | `cached_start`        | `text-3`     | Cached memory start      |
//! | `cached_mid`          | `accent`     | Cached memory mid        |
//! | `cached_end`          | `urgent`     | Cached memory end        |
//! | `available_start`     | `ok`         | Available memory start   |
//! | `available_mid`       | `accent`     | Available memory mid     |
//! | `available_end`       | `text-3`     | Available memory end     |
//! | `used_start`          | `accent`     | Used memory start        |
//! | `used_mid`            | `urgent`     | Used memory mid          |
//! | `used_end`            | `urgent`     | Used memory end          |

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// btop theme generator.
pub struct Btop;

impl ThemeGenerator for Btop {
    fn name(&self) -> &str {
        "btop"
    }

    fn relative_path(&self) -> &str {
        "btop/garden.theme"
    }

    fn generate(&self, palette: &Palette) -> String {
        let c = |role: ColorRole| palette.color(role).unwrap().as_str();

        let base = c(ColorRole::Base);
        let base_hl = c(ColorRole::BaseHl);
        let border_sub = c(ColorRole::BorderSub);
        let border = c(ColorRole::Border);
        let text1 = c(ColorRole::Text1);
        let text2 = c(ColorRole::Text2);
        let text3 = c(ColorRole::Text3);
        let text4 = c(ColorRole::Text4);
        let accent = c(ColorRole::Accent);
        let urgent = c(ColorRole::Urgent);
        let ok = c(ColorRole::Ok);

        format!(
            "\
# Garden theme — {name} {icon}
# Generated by garden-themes. Do not edit by hand.

# Main
theme[main_bg]=\"{base}\"
theme[main_fg]=\"{text2}\"
theme[title]=\"{text1}\"
theme[hi_fg]=\"{accent}\"
theme[selected_bg]=\"{base_hl}\"
theme[selected_fg]=\"{text1}\"
theme[inactive_fg]=\"{text4}\"
theme[graph_text]=\"{text3}\"
theme[meter_bg]=\"{border_sub}\"
theme[proc_misc]=\"{text3}\"

# Box borders
theme[cpu_box]=\"{border}\"
theme[mem_box]=\"{border}\"
theme[net_box]=\"{border}\"
theme[proc_box]=\"{border}\"
theme[div_line]=\"{border_sub}\"

# Temperature gradient
theme[temp_start]=\"{accent}\"
theme[temp_mid]=\"{urgent}\"
theme[temp_end]=\"{urgent}\"

# CPU gradient
theme[cpu_start]=\"{accent}\"
theme[cpu_mid]=\"{ok}\"
theme[cpu_end]=\"{urgent}\"

# Free memory gradient
theme[free_start]=\"{ok}\"
theme[free_mid]=\"{accent}\"
theme[free_end]=\"{text3}\"

# Cached memory gradient
theme[cached_start]=\"{text3}\"
theme[cached_mid]=\"{accent}\"
theme[cached_end]=\"{urgent}\"

# Available memory gradient
theme[available_start]=\"{ok}\"
theme[available_mid]=\"{accent}\"
theme[available_end]=\"{text3}\"

# Used memory gradient
theme[used_start]=\"{accent}\"
theme[used_mid]=\"{urgent}\"
theme[used_end]=\"{urgent}\"

# Download gradient
theme[download_start]=\"{accent}\"
theme[download_mid]=\"{ok}\"
theme[download_end]=\"{text3}\"

# Upload gradient
theme[upload_start]=\"{accent}\"
theme[upload_mid]=\"{urgent}\"
theme[upload_end]=\"{text3}\"

# Process gradient
theme[process_start]=\"{accent}\"
theme[process_mid]=\"{ok}\"
theme[process_end]=\"{urgent}\"
",
            name = palette.name,
            icon = palette.icon,
        )
    }
}
