//! Fish shell syntax-highlighting theme generator.
//!
//! Produces a `fish/garden-theme.fish` file that sets the
//! `fish_color_*` universal variables mapping Garden's semantic roles
//! to fish's syntax highlighting categories.
//!
//! The generated file uses `set -U` (universal variables) so colors
//! persist across sessions and are applied immediately without
//! restarting fish.
//!
//! # Color mapping
//!
//! | fish variable              | Palette role | Rationale                  |
//! |----------------------------|-------------|----------------------------|
//! | `fish_color_normal`        | `text-2`    | Default body text          |
//! | `fish_color_command`       | `text-1`    | Recognized commands        |
//! | `fish_color_keyword`       | `text-3`    | Language keywords          |
//! | `fish_color_quote`         | `accent`    | Quoted strings             |
//! | `fish_color_error`         | `urgent`    | Syntax / runtime errors    |
//! | `fish_color_param`         | `text-2`    | Command parameters         |
//! | `fish_color_comment`       | `text-4`    | Comments                   |
//! | `fish_color_autosuggestion`| `text-4`    | Ghost suggestions          |
//! | `fish_color_selection`     | (bg only)   | Selected text background   |
//! | `fish_color_operator`      | `text-3`    | Operators (&&, ||, etc.)   |
//! | `fish_color_escape`        | `accent`    | Escape sequences (\n, etc.)|
//! | `fish_color_redirection`   | `text-3`    | Pipes and redirections     |
//! | `fish_color_end`           | `text-3`    | Statement terminators      |

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// Fish shell theme generator.
///
/// Generates a fish configuration snippet that sets universal color
/// variables for syntax highlighting. Source this file from
/// `~/.config/fish/conf.d/` or include it via the Garden palette
/// aspect.
pub struct Fish;

impl ThemeGenerator for Fish {
    fn name(&self) -> &str {
        "fish"
    }

    fn relative_path(&self) -> &str {
        "fish/garden-theme.fish"
    }

    fn generate(&self, palette: &Palette) -> String {
        // Helper: look up a role and return bare hex (no #).
        let bare = |role: ColorRole| -> &str {
            palette
                .color(role)
                .expect("palette should be validated before generation")
                .bare()
        };

        format!(
            "\
# Garden theme — {name} {icon}
# Generated by garden-themes. Do not edit by hand.

set -U fish_color_normal {text2}
set -U fish_color_command {text1}
set -U fish_color_keyword {text3}
set -U fish_color_quote {accent}
set -U fish_color_error {urgent}
set -U fish_color_param {text2}
set -U fish_color_comment {text4}
set -U fish_color_autosuggestion {text4}
set -U fish_color_selection --background={base_hl}
set -U fish_color_operator {text3}
set -U fish_color_escape {accent}
set -U fish_color_redirection {text3}
set -U fish_color_end {text3}
",
            name = palette.name,
            icon = palette.icon,
            text1 = bare(ColorRole::Text1),
            text2 = bare(ColorRole::Text2),
            text3 = bare(ColorRole::Text3),
            text4 = bare(ColorRole::Text4),
            accent = bare(ColorRole::Accent),
            urgent = bare(ColorRole::Urgent),
            base_hl = bare(ColorRole::BaseHl),
        )
    }
}
