//! fzf fuzzy-finder theme generator.
//!
//! Produces `fzf/garden-theme.fish` — a fish snippet that sets
//! `FZF_DEFAULT_OPTS` with the current palette colors. Source this
//! file from fish init so every new fzf invocation uses the active
//! palette.
//!
//! # Color mapping
//!
//! | fzf token   | Palette role | Rationale              |
//! |-------------|-------------|------------------------|
//! | `bg`        | `base`      | Main background        |
//! | `bg+`       | `base-hl`   | Selected row highlight |
//! | `fg`        | `text-2`    | Default text           |
//! | `fg+`       | `text-1`    | Selected row text      |
//! | `hl`        | `urgent`    | Match highlight        |
//! | `hl+`       | `urgent`    | Match highlight (sel.) |
//! | `info`      | `text-3`    | Info line              |
//! | `prompt`    | `accent`    | Prompt character       |
//! | `pointer`   | `text-1`    | Selection pointer      |
//! | `marker`    | `accent`    | Multi-select marker    |
//! | `spinner`   | `accent`    | Loading spinner        |
//! | `header`    | `text-3`    | Header text            |
//! | `border`    | `border`    | Border color           |

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// fzf theme generator.
pub struct Fzf;

impl ThemeGenerator for Fzf {
    fn name(&self) -> &str {
        "fzf"
    }

    fn relative_path(&self) -> &str {
        "fzf/garden-theme.fish"
    }

    fn generate(&self, palette: &Palette) -> String {
        let c = |role: ColorRole| palette.color(role).unwrap();

        format!(
            "\
# Garden theme — {name} {icon}
# Generated by garden-themes. Do not edit by hand.
#
# Sets FZF_DEFAULT_OPTS with palette colors. Source from fish init
# or conf.d so every fzf invocation picks up the active palette.

set -gx FZF_DEFAULT_OPTS \
  --color=bg+:{base_hl},bg:{base},spinner:{accent},hl:{urgent} \
  --color=fg:{text2},header:{text3},info:{text3},pointer:{text1} \
  --color=marker:{accent},fg+:{text1},prompt:{accent},hl+:{urgent} \
  --color=border:{border} \
  --border
",
            name = palette.name,
            icon = palette.icon,
            base = c(ColorRole::Base),
            base_hl = c(ColorRole::BaseHl),
            text1 = c(ColorRole::Text1),
            text2 = c(ColorRole::Text2),
            text3 = c(ColorRole::Text3),
            accent = c(ColorRole::Accent),
            urgent = c(ColorRole::Urgent),
            border = c(ColorRole::Border),
        )
    }
}
