//! Kakoune editor theme generator.
//!
//! Produces a `kak/garden.kak` file that maps Garden's 13
//! semantic color roles to kakoune's `face global` declarations using
//! the `rgb:rrggbb` color format.
//!
//! # Face mapping
//!
//! ## UI faces
//!
//! | Face               | Foreground   | Background   | Attrs |
//! |--------------------|-------------|-------------|-------|
//! | `Default`          | `text-2`    | `base`      |       |
//! | `StatusLine`       | `text-3`    | `base-deep` |       |
//! | `StatusLineMode`   | `text-1`    | `base-deep` |       |
//! | `StatusLineInfo`   | `text-4`    | `base-deep` |       |
//! | `StatusLineValue`  | `accent`    | `base-deep` |       |
//! | `StatusCursor`     | `base-deep` | `text-1`    |       |
//! | `Prompt`           | `accent`    | `base-deep` |       |
//! | `MenuForeground`   | `text-1`    | `base-hl`   |       |
//! | `MenuBackground`   | `text-2`    | `base-raised`|      |
//! | `Information`      | `text-2`    | `base-raised`|      |
//! | `Error`            | `urgent`    | `base`      |       |
//!
//! ## Selection faces
//!
//! | Face                 | Foreground | Background   | Attrs |
//! |----------------------|-----------|-------------|-------|
//! | `PrimarySelection`   | `default` | `base-hl`   | `+g`  |
//! | `SecondarySelection` | `default` | `base-raised`| `+g`  |
//! | `PrimaryCursor`      | `base-deep`| `text-1`   |       |
//! | `SecondaryCursor`    | `base-deep`| `text-2`   |       |
//!
//! ## Gutter faces
//!
//! | Face                 | Foreground   |
//! |----------------------|-------------|
//! | `LineNumbers`        | `text-4`    |
//! | `LineNumberCursor`   | `text-3`    |
//! | `LineNumbersWrapped` | `border-sub`|
//!
//! ## Syntax faces
//!
//! | Face            | Color        | Attrs |
//! |-----------------|-------------|-------|
//! | `value`         | `accent`    |       |
//! | `type`          | `text-2`    |       |
//! | `variable`      | `text-1`    |       |
//! | `module`        | `text-2`    |       |
//! | `function`      | `text-1`    |       |
//! | `string`        | `ok`        |       |
//! | `keyword`       | `text-3`    |       |
//! | `operator`      | `text-3`    |       |
//! | `attribute`     | `accent`    |       |
//! | `comment`       | `text-4`    | `+i`  |
//! | `documentation` | `text-3`    |       |
//! | `meta`          | `accent`    |       |
//! | `builtin`       | `text-2`    | `+b`  |

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// Kakoune theme generator.
///
/// Generates a kakoune colorscheme file with `face global` declarations.
/// Place the output in `~/.config/kak/colors/` and activate with
/// `colorscheme garden` in your `kakrc`.
pub struct Kakoune;

impl ThemeGenerator for Kakoune {
    fn name(&self) -> &str {
        "kakoune"
    }

    fn relative_path(&self) -> &str {
        "kak/garden.kak"
    }

    fn generate(&self, palette: &Palette) -> String {
        // Helper: look up a role and return `rgb:rrggbb`.
        let rgb = |role: ColorRole| -> String {
            let bare = palette
                .color(role)
                .expect("palette should be validated before generation")
                .bare();
            format!("rgb:{bare}")
        };

        let base = rgb(ColorRole::Base);
        let base_deep = rgb(ColorRole::BaseDeep);
        let base_raised = rgb(ColorRole::BaseRaised);
        let base_hl = rgb(ColorRole::BaseHl);
        let border_sub = rgb(ColorRole::BorderSub);
        let text1 = rgb(ColorRole::Text1);
        let text2 = rgb(ColorRole::Text2);
        let text3 = rgb(ColorRole::Text3);
        let text4 = rgb(ColorRole::Text4);
        let accent = rgb(ColorRole::Accent);
        let urgent = rgb(ColorRole::Urgent);
        let ok = rgb(ColorRole::Ok);

        format!(
            "\
# Garden theme — {name} {icon}
# Generated by garden-themes. Do not edit by hand.

# UI
face global Default            {text2},{base}
face global StatusLine         {text3},{base_deep}
face global StatusLineMode     {text1},{base_deep}
face global StatusLineInfo     {text4},{base_deep}
face global StatusLineValue    {accent},{base_deep}
face global StatusCursor       {base_deep},{text1}
face global Prompt             {accent},{base_deep}
face global MenuForeground     {text1},{base_hl}
face global MenuBackground     {text2},{base_raised}
face global Information        {text2},{base_raised}
face global Error              {urgent},{base}

# Selections
face global PrimarySelection   default,{base_hl}+g
face global SecondarySelection default,{base_raised}+g
face global PrimaryCursor      {base_deep},{text1}
face global SecondaryCursor    {base_deep},{text2}

# Line numbers
face global LineNumbers        {text4}
face global LineNumberCursor   {text3}
face global LineNumbersWrapped {border_sub}

# Matching & whitespace
face global MatchingChar       {accent}+b
face global Whitespace         {border_sub}
face global BufferPadding      {border_sub}

# Syntax
face global value              {accent}
face global type               {text2}
face global variable           {text1}
face global module             {text2}
face global function           {text1}
face global string             {ok}
face global keyword            {text3}
face global operator           {text3}
face global attribute          {accent}
face global comment            {text4}+i
face global documentation      {text3}
face global meta               {accent}
face global builtin            {text2}+b
",
            name = palette.name,
            icon = palette.icon,
        )
    }
}
