//! Kitty terminal emulator theme generator.
//!
//! Produces a `kitty/garden-theme.conf` file that maps Garden's 13
//! semantic color roles to kitty's color settings: foreground,
//! background, cursor, selection, and the 16 ANSI color slots.
//!
//! # ANSI mapping
//!
//! The standard 8 colors (0–7) use the darker/primary role for each
//! semantic slot, while the bright variants (8–15) use the next-lighter
//! role in the palette hierarchy where available.
//!
//! | ANSI slot        | Normal (0–7)  | Bright (8–15) |
//! |------------------|---------------|---------------|
//! | black   (0 / 8)  | `base-deep`   | `border`      |
//! | red     (1 / 9)  | `urgent`      | `urgent`      |
//! | green   (2 / 10) | `ok`          | `ok`          |
//! | yellow  (3 / 11) | `accent`      | `accent`      |
//! | blue    (4 / 12) | `text-3`      | `text-2`      |
//! | magenta (5 / 13) | `border`      | `text-3`      |
//! | cyan    (6 / 14) | `text-2`      | `text-1`      |
//! | white   (7 / 15) | `text-2`      | `text-1`      |

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// Kitty theme generator.
///
/// Generates a kitty color configuration fragment suitable for
/// inclusion via `include garden-theme.conf` in the main `kitty.conf`.
pub struct Kitty;

impl ThemeGenerator for Kitty {
    fn name(&self) -> &str {
        "kitty"
    }

    fn relative_path(&self) -> &str {
        "kitty/garden-theme.conf"
    }

    fn generate(&self, palette: &Palette) -> String {
        // Helper: look up a role and return its `#rrggbb` value.
        let c = |role: ColorRole| -> &str {
            palette
                .color(role)
                .expect("palette should be validated before generation")
                .as_str()
        };

        format!(
            "\
# Garden theme — {name} {icon}
# Generated by garden-themes. Do not edit by hand.

# Special colors
background {base}
foreground {text1}
cursor {text1}
cursor_text_color {base}
selection_background {base_hl}
selection_foreground {text1}
url_color {accent}

# Normal colors (0–7)
color0 {base_deep}
color1 {urgent}
color2 {ok}
color3 {accent}
color4 {text3}
color5 {border}
color6 {text2}
color7 {text2}

# Bright colors (8–15)
color8 {border_bright}
color9 {urgent_bright}
color10 {ok_bright}
color11 {accent_bright}
color12 {text2_bright}
color13 {text3_bright}
color14 {text1_bright}
color15 {text1_bright2}
",
            name = palette.name,
            icon = palette.icon,
            base = c(ColorRole::Base),
            text1 = c(ColorRole::Text1),
            base_hl = c(ColorRole::BaseHl),
            accent = c(ColorRole::Accent),
            // Normal 0–7
            base_deep = c(ColorRole::BaseDeep),
            urgent = c(ColorRole::Urgent),
            ok = c(ColorRole::Ok),
            text3 = c(ColorRole::Text3),
            border = c(ColorRole::Border),
            text2 = c(ColorRole::Text2),
            // Bright 8–15
            border_bright = c(ColorRole::Border),
            urgent_bright = c(ColorRole::Urgent),
            ok_bright = c(ColorRole::Ok),
            accent_bright = c(ColorRole::Accent),
            text2_bright = c(ColorRole::Text2),
            text3_bright = c(ColorRole::Text3),
            text1_bright = c(ColorRole::Text1),
            text1_bright2 = c(ColorRole::Text1),
        )
    }
}
