//! lazygit theme generator.
//!
//! Produces `lazygit/garden.yml` — a partial lazygit config containing
//! only the `gui.theme` block. Merge this with your base lazygit config
//! via `LG_CONFIG_FILE` (comma-separated list).
//!
//! # Color mapping
//!
//! | lazygit key                 | Palette role | Rationale              |
//! |-----------------------------|-------------|------------------------|
//! | `activeBorderColor`         | `accent`    | Active pane border     |
//! | `inactiveBorderColor`       | `border`    | Inactive pane border   |
//! | `searchingActiveBorderColor`| `accent`    | Search-active border   |
//! | `optionsTextColor`          | `text-3`    | Bottom option hints    |
//! | `selectedLineBgColor`       | `base-hl`   | Selected line bg       |
//! | `cherryPickedCommitFgColor` | `accent`    | Cherry-pick fg         |
//! | `cherryPickedCommitBgColor` | `base-hl`   | Cherry-pick bg         |
//! | `markedBaseCommitFgColor`   | `accent`    | Marked base commit fg  |
//! | `markedBaseCommitBgColor`   | `base-hl`   | Marked base commit bg  |
//! | `unstagedChangesColor`      | `urgent`    | Unstaged changes       |
//! | `defaultFgColor`            | `text-2`    | Default foreground     |

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// lazygit theme generator.
pub struct Lazygit;

impl ThemeGenerator for Lazygit {
    fn name(&self) -> &str {
        "lazygit"
    }

    fn relative_path(&self) -> &str {
        "lazygit/garden.yml"
    }

    fn generate(&self, palette: &Palette) -> String {
        let c = |role: ColorRole| palette.color(role).unwrap().as_str();

        let accent = c(ColorRole::Accent);
        let border = c(ColorRole::Border);
        let text2 = c(ColorRole::Text2);
        let text3 = c(ColorRole::Text3);
        let base_hl = c(ColorRole::BaseHl);
        let urgent = c(ColorRole::Urgent);

        format!(
            "\
# Garden theme — {name} {icon}
# Generated by garden-themes. Do not edit by hand.

gui:
  theme:
    activeBorderColor:
      - \"{accent}\"
      - bold
    inactiveBorderColor:
      - \"{border}\"
    searchingActiveBorderColor:
      - \"{accent}\"
      - bold
    optionsTextColor:
      - \"{text3}\"
    selectedLineBgColor:
      - \"{base_hl}\"
    cherryPickedCommitFgColor:
      - \"{accent}\"
    cherryPickedCommitBgColor:
      - \"{base_hl}\"
    markedBaseCommitFgColor:
      - \"{accent}\"
    markedBaseCommitBgColor:
      - \"{base_hl}\"
    unstagedChangesColor:
      - \"{urgent}\"
    defaultFgColor:
      - \"{text2}\"
",
            name = palette.name,
            icon = palette.icon,
        )
    }
}
