//! Niri compositor theme generator — **reference output only**.
//!
//! Produces `niri/garden-colors.kdl` showing the current palette's niri
//! color values. This file is **not** wired into niri's config because
//! niri (as of 25.05) does not support `include` directives.
//!
//! Niri border/background colors are instead set at Nix eval time via
//! `programs.niri.settings` and only change on `nixos-rebuild switch`.
//! This generator is kept for reference and for future use if niri adds
//! include or runtime color IPC support.
//!
//! # Color mapping
//!
//! | niri setting                      | Palette role | Rationale           |
//! |-----------------------------------|-------------|---------------------|
//! | `background-color`                | `base-deep` | Output background   |
//! | HPC window-rule `active-color`    | `urgent`    | High-priority hosts |
//! | GPU window-rule `active-color`    | `accent`    | GPU cluster hosts   |
//! | Homelab window-rule `active-color`| `ok`        | Homelab hosts       |

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// Niri theme generator.
pub struct Niri;

impl ThemeGenerator for Niri {
    fn name(&self) -> &str {
        "niri"
    }

    fn relative_path(&self) -> &str {
        "niri/garden-colors.kdl"
    }

    fn generate(&self, palette: &Palette) -> String {
        let c = |role: ColorRole| palette.color(role).unwrap().as_str();

        let base_deep = c(ColorRole::BaseDeep);
        let urgent = c(ColorRole::Urgent);
        let accent = c(ColorRole::Accent);
        let ok = c(ColorRole::Ok);

        // NOTE: We intentionally omit layout.border colors here.
        // Niri's include replaces the entire `layout` block, which would
        // wipe out gaps, focus-ring, preset-widths, etc. Border colors
        // are set in the main config via programs.niri.settings instead.
        // Only background-color (top-level) and window-rule (additive)
        // are safe to include.
        format!(
            "\
// Garden theme — {name} {icon}
// Generated by garden-themes. Do not edit by hand.

background-color \"{base_deep}\"

// Host tier borders — HPC (urgent)
window-rule {{
    match title=\"frontier\"
    match title=\"andes\"
    match title=\"summit\"
    border {{ active-color \"{urgent}\"; }}
}}

// Host tier borders — GPU (accent)
window-rule {{
    match title=\"dgx-\"
    border {{ active-color \"{accent}\"; }}
}}

// Host tier borders — Homelab (ok)
window-rule {{
    match title=\"homelab\"
    border {{ active-color \"{ok}\"; }}
}}
",
            name = palette.name,
            icon = palette.icon,
        )
    }
}
