//! Obsidian knowledge-base theme generator.
//!
//! Produces an `obsidian/garden-theme.css` file — a CSS snippet that
//! overrides Obsidian's dark-mode variables to match the active Garden
//! palette.  Users enable it in Obsidian → Settings → Appearance →
//! CSS snippets.
//!
//! # HSL decomposition
//!
//! Obsidian's accent system expects `--accent-h`, `--accent-s`, and
//! `--accent-l` as separate HSL components.  We compute these from
//! the palette's hex accent at generation time so the values are
//! correct for every palette, not just a single hard-coded one.

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// Obsidian theme generator.
pub struct Obsidian;

/// Convert RGB (0–255) to HSL.  Returns `(h, s, l)` where `h` is in
/// degrees (0–360) and `s`/`l` are in 0.0–1.0.
fn rgb_to_hsl(r: u8, g: u8, b: u8) -> (f64, f64, f64) {
    let r = r as f64 / 255.0;
    let g = g as f64 / 255.0;
    let b = b as f64 / 255.0;

    let max = r.max(g).max(b);
    let min = r.min(g).min(b);
    let l = (max + min) / 2.0;

    if (max - min).abs() < f64::EPSILON {
        return (0.0, 0.0, l);
    }

    let d = max - min;
    let s = if l > 0.5 {
        d / (2.0 - max - min)
    } else {
        d / (max + min)
    };

    let h = if (max - r).abs() < f64::EPSILON {
        let mut h = (g - b) / d;
        if g < b {
            h += 6.0;
        }
        h
    } else if (max - g).abs() < f64::EPSILON {
        (b - r) / d + 2.0
    } else {
        (r - g) / d + 4.0
    };

    (h * 60.0, s, l)
}

impl ThemeGenerator for Obsidian {
    fn name(&self) -> &str {
        "obsidian"
    }

    fn relative_path(&self) -> &str {
        "obsidian/garden-theme.css"
    }

    fn generate(&self, palette: &Palette) -> String {
        let c = |role: ColorRole| -> &str {
            palette
                .color(role)
                .expect("palette should be validated before generation")
                .as_str()
        };

        // HSL decomposition of accent for Obsidian's accent system.
        let accent_color = palette
            .color(ColorRole::Accent)
            .expect("palette should be validated before generation");
        let (h, s, l) = rgb_to_hsl(accent_color.r(), accent_color.g(), accent_color.b());

        format!(
            "\
/* Garden theme — {name} {icon} */
/* Generated by garden-themes. Do not edit by hand. */

.theme-dark {{
  /* Backgrounds */
  --background-primary: {base};
  --background-primary-alt: {base_raised};
  --background-secondary: {base_deep};
  --background-secondary-alt: {base_deep};

  /* Hover / selection */
  --background-modifier-hover: {base_hl};

  /* Borders */
  --background-modifier-border: {border};
  --background-modifier-border-hover: {border};
  --background-modifier-border-focus: {accent};

  /* Text hierarchy */
  --text-normal: {text2};
  --text-muted: {text3};
  --text-faint: {text4};
  --text-on-accent: {text1};

  /* Accent — HSL decomposition of {accent} */
  --accent-h: {accent_h:.0};
  --accent-s: {accent_s:.0}%;
  --accent-l: {accent_l:.0}%;
  --color-accent: {accent};
  --color-accent-1: {accent};
  --interactive-accent: {accent};

  /* Semantic */
  --text-error: {urgent};
  --text-success: {ok};

  /* Headings */
  --h1-color: {text1};
  --h2-color: {text1};
  --h3-color: {text1};
  --h4-color: {text1};
  --h5-color: {text1};
  --h6-color: {text1};

  /* Fonts — match system */
  --default-font: \"M PLUS 1p\", \"IBM Plex Sans\", sans-serif;
  --font-monospace: \"IBM Plex Mono\", \"JetBrains Mono\", monospace;
}}
",
            name = palette.name,
            icon = palette.icon,
            base = c(ColorRole::Base),
            base_raised = c(ColorRole::BaseRaised),
            base_deep = c(ColorRole::BaseDeep),
            base_hl = c(ColorRole::BaseHl),
            border = c(ColorRole::Border),
            accent = c(ColorRole::Accent),
            text1 = c(ColorRole::Text1),
            text2 = c(ColorRole::Text2),
            text3 = c(ColorRole::Text3),
            text4 = c(ColorRole::Text4),
            urgent = c(ColorRole::Urgent),
            ok = c(ColorRole::Ok),
            accent_h = h,
            accent_s = s * 100.0,
            accent_l = l * 100.0,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pure_red() {
        let (h, s, l) = rgb_to_hsl(255, 0, 0);
        assert!((h - 0.0).abs() < 0.5);
        assert!((s - 1.0).abs() < 0.01);
        assert!((l - 0.5).abs() < 0.01);
    }

    #[test]
    fn pure_green() {
        let (h, s, l) = rgb_to_hsl(0, 255, 0);
        assert!((h - 120.0).abs() < 0.5);
        assert!((s - 1.0).abs() < 0.01);
        assert!((l - 0.5).abs() < 0.01);
    }

    #[test]
    fn pure_blue() {
        let (h, s, l) = rgb_to_hsl(0, 0, 255);
        assert!((h - 240.0).abs() < 0.5);
        assert!((s - 1.0).abs() < 0.01);
        assert!((l - 0.5).abs() < 0.01);
    }

    #[test]
    fn grey() {
        let (h, s, l) = rgb_to_hsl(128, 128, 128);
        assert!((h - 0.0).abs() < 0.5);
        assert!((s - 0.0).abs() < 0.01);
        assert!((l - 0.502).abs() < 0.01);
    }
}
