//! yazi file manager theme generator.
//!
//! Produces `yazi/garden-theme.toml` — a yazi theme file in TOML format
//! covering the manager, status, select, and input sections.
//!
//! # Color mapping
//!
//! ## Manager
//!
//! | Element          | Foreground | Background  |
//! |------------------|-----------|-------------|
//! | `cwd`            | `accent`  |             |
//! | `hovered` (bg)   |           | `base-hl`   |
//! | `tab_active` fg  | `text-1`  | `base-hl`   |
//! | `tab_inactive` fg| `text-4`  |             |
//! | `find_keyword`   | `accent`  |             |
//! | `find_position`  | `text-3`  |             |
//! | `marker_selected`| `accent`  |             |
//! | `marker_copied`  | `ok`      |             |
//! | `marker_cut`     | `urgent`  |             |
//!
//! ## Status
//!
//! | Element       | Foreground | Background  |
//! |---------------|-----------|-------------|
//! | `separator`   | `border`  |             |
//! | `mode_normal` | `base`    | `accent`    |
//! | `mode_select` | `base`    | `urgent`    |
//! | `mode_unset`  | `base`    | `text-3`    |
//!
//! ## Select & Input
//!
//! | Element        | Foreground | Background  |
//! |----------------|-----------|-------------|
//! | `border`       | `border`  |             |
//! | `active`       | `accent`  |             |
//! | `inactive`     | `text-4`  |             |

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// yazi theme generator.
pub struct Yazi;

impl ThemeGenerator for Yazi {
    fn name(&self) -> &str {
        "yazi"
    }

    fn relative_path(&self) -> &str {
        "yazi/garden-theme.toml"
    }

    fn generate(&self, palette: &Palette) -> String {
        let c = |role: ColorRole| palette.color(role).unwrap().as_str();

        let base = c(ColorRole::Base);
        let base_hl = c(ColorRole::BaseHl);
        let border = c(ColorRole::Border);
        let text1 = c(ColorRole::Text1);
        let text3 = c(ColorRole::Text3);
        let text4 = c(ColorRole::Text4);
        let accent = c(ColorRole::Accent);
        let urgent = c(ColorRole::Urgent);
        let ok = c(ColorRole::Ok);

        format!(
            "\
# Garden theme — {name} {icon}
# Generated by garden-themes. Do not edit by hand.

[manager]
cwd = {{ fg = \"{accent}\" }}

hovered = {{ bg = \"{base_hl}\" }}
preview_hovered = {{ bg = \"{base_hl}\" }}

find_keyword = {{ fg = \"{accent}\", bold = true }}
find_position = {{ fg = \"{text3}\", italic = true }}

marker_selected = {{ fg = \"{accent}\", bold = true }}
marker_copied = {{ fg = \"{ok}\", bold = true }}
marker_cut = {{ fg = \"{urgent}\", bold = true }}

tab_active = {{ fg = \"{text1}\", bg = \"{base_hl}\" }}
tab_inactive = {{ fg = \"{text4}\" }}
tab_width = 1

count_selected = {{ fg = \"{base}\", bg = \"{accent}\" }}
count_copied = {{ fg = \"{base}\", bg = \"{ok}\" }}
count_cut = {{ fg = \"{base}\", bg = \"{urgent}\" }}

[status]
separator_open = \"\"
separator_close = \"\"
separator_style = {{ fg = \"{border}\" }}

mode_normal = {{ fg = \"{base}\", bg = \"{accent}\", bold = true }}
mode_select = {{ fg = \"{base}\", bg = \"{urgent}\", bold = true }}
mode_unset = {{ fg = \"{base}\", bg = \"{text3}\", bold = true }}

progress_label = {{ fg = \"{text1}\", bold = true }}
progress_normal = {{ fg = \"{accent}\" }}
progress_error = {{ fg = \"{urgent}\" }}

[select]
border = {{ fg = \"{border}\" }}
active = {{ fg = \"{accent}\", bold = true }}
inactive = {{ fg = \"{text4}\" }}

[input]
border = {{ fg = \"{border}\" }}
title = {{ fg = \"{text1}\" }}
value = {{ fg = \"{accent}\" }}
selected = {{ bg = \"{base_hl}\" }}
",
            name = palette.name,
            icon = palette.icon,
        )
    }
}
