//! zathura document viewer theme generator.
//!
//! Produces `zathura/gardenrc` — a zathurarc fragment using `set`
//! commands. Source this from the main zathurarc via `include`.
//!
//! # Color mapping
//!
//! | zathura key                | Palette role  | Rationale            |
//! |----------------------------|--------------|----------------------|
//! | `default-fg`               | `text-2`     | Default foreground   |
//! | `default-bg`               | `base`       | Default background   |
//! | `statusbar-fg`             | `text-3`     | Status bar text      |
//! | `statusbar-bg`             | `base-deep`  | Status bar bg        |
//! | `inputbar-fg`              | `text-1`     | Input bar text       |
//! | `inputbar-bg`              | `base-deep`  | Input bar bg         |
//! | `notification-fg`          | `text-2`     | Notification text    |
//! | `notification-bg`          | `base-raised`| Notification bg      |
//! | `notification-error-fg`    | `urgent`     | Error notification   |
//! | `notification-error-bg`    | `base-raised`| Error notification bg|
//! | `notification-warning-fg`  | `accent`     | Warning notification |
//! | `notification-warning-bg`  | `base-raised`| Warning notif. bg    |
//! | `highlight-color`          | `base-hl`    | Search highlight     |
//! | `highlight-active-color`   | `accent`     | Active match         |
//! | `completion-fg`            | `text-2`     | Completion text      |
//! | `completion-bg`            | `base-raised`| Completion bg        |
//! | `completion-highlight-fg`  | `text-1`     | Selected completion  |
//! | `completion-highlight-bg`  | `base-hl`    | Selected compl. bg   |
//! | `completion-group-fg`      | `text-3`     | Completion group     |
//! | `completion-group-bg`      | `base-deep`  | Completion group bg  |
//! | `recolor-lightcolor`       | `base`       | Recolor light areas  |
//! | `recolor-darkcolor`        | `text-1`     | Recolor dark areas   |
//! | `index-fg`                 | `text-2`     | Index foreground     |
//! | `index-bg`                 | `base`       | Index background     |
//! | `index-active-fg`          | `text-1`     | Active index item    |
//! | `index-active-bg`          | `base-hl`    | Active index bg      |

use garden_core::{ColorRole, Palette};

use super::ThemeGenerator;

/// zathura theme generator.
pub struct Zathura;

impl ThemeGenerator for Zathura {
    fn name(&self) -> &str {
        "zathura"
    }

    fn relative_path(&self) -> &str {
        "zathura/gardenrc"
    }

    fn generate(&self, palette: &Palette) -> String {
        let c = |role: ColorRole| palette.color(role).unwrap().as_str();

        let base = c(ColorRole::Base);
        let base_deep = c(ColorRole::BaseDeep);
        let base_raised = c(ColorRole::BaseRaised);
        let base_hl = c(ColorRole::BaseHl);
        let text1 = c(ColorRole::Text1);
        let text2 = c(ColorRole::Text2);
        let text3 = c(ColorRole::Text3);
        let accent = c(ColorRole::Accent);
        let urgent = c(ColorRole::Urgent);

        format!(
            "\
# Garden theme — {name} {icon}
# Generated by garden-themes. Do not edit by hand.

set default-fg \"{text2}\"
set default-bg \"{base}\"

set statusbar-fg \"{text3}\"
set statusbar-bg \"{base_deep}\"

set inputbar-fg \"{text1}\"
set inputbar-bg \"{base_deep}\"

set notification-fg \"{text2}\"
set notification-bg \"{base_raised}\"
set notification-error-fg \"{urgent}\"
set notification-error-bg \"{base_raised}\"
set notification-warning-fg \"{accent}\"
set notification-warning-bg \"{base_raised}\"

set highlight-color \"{base_hl}\"
set highlight-active-color \"{accent}\"

set completion-fg \"{text2}\"
set completion-bg \"{base_raised}\"
set completion-highlight-fg \"{text1}\"
set completion-highlight-bg \"{base_hl}\"
set completion-group-fg \"{text3}\"
set completion-group-bg \"{base_deep}\"

set recolor-lightcolor \"{base}\"
set recolor-darkcolor \"{text1}\"
set recolor true

set index-fg \"{text2}\"
set index-bg \"{base}\"
set index-active-fg \"{text1}\"
set index-active-bg \"{base_hl}\"
",
            name = palette.name,
            icon = palette.icon,
        )
    }
}
